version: 0.0
os: linux
files:
  - source: dist/angular/
    destination: /usr/share/nginx/html/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/beforeinstall_application
      timeout: 300
      runas: root


  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/status_application
      timeout: 300
      runas: root

