const cardData = [
    {
        icon: 'fe-tag',
        tickets: 150,
        title: 'Total Codes',
        text: '',
    },
    {
        icon: 'fe-tag',
        tickets: 80,
        title: 'Used Codes',
        text: 'warning'
    },
    {
        icon: 'fe-tag',
        tickets: 40,
        title: 'Unused Codes',
        text: 'success'
    },
    {
        icon: 'fe-tag',
        tickets: 20,
        title: 'Expired Codes',
        text: 'danger'
    }
];

const tableData = [
    {
        id: '#1020',
        requestuser: 'assets/images/users/user-9.jpg',
        name: 'Erwin E. Brown',
        subject: 'A new rating has been received',
        assignuser: 'assets/images/users/user-1.jpg',
        priority: 'Medium',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Used',
        createddate: '2020/04/30',
        duedate: '2020/08/07',

    },
    {
        id: '#1254',
        requestuser: 'assets/images/users/user-8.jpg',
        name: 'Margeret V. Ligon',
        subject: 'Your application has been received!',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'High',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'New',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#1256',
        requestuser: 'assets/images/users/user-2.jpg',
        name: 'George A. Lianes',
        subject: 'Support for theme',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'Low',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#1352',
        requestuser: 'assets/images/users/user-5.jpg',
        name: 'Karen R. Doyle',
        subject: 'Question regarding your Bootstrap Theme',
        assignuser: 'assets/images/users/user-8.jpg',
        priority: 'High',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#2251',
        requestuser: 'assets/images/users/user-8.jpg',
        name: 'Mark C. Diaz',
        subject: 'Verify your new email address!',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'High',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#2542',
        requestuser: 'assets/images/users/user-3.jpg',
        name: 'Jose D. Delacruz',
        subject: 'New submission on your website',
        assignuser: 'assets/images/users/user-9.jpg',
        priority: 'Medium',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#320',
        requestuser: 'assets/images/users/user-5.jpg',
        name: 'Phyllis K. Maciel',
        subject: 'Verify your new email address!',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'High',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#3562',
        requestuser: 'assets/images/users/user-8.jpg',
        name: 'Freddie J. Plourde',
        subject: 'Security alert for my account',
        assignuser: 'assets/images/users/user-2.jpg',
        priority: 'Low',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#3653',
        requestuser: 'assets/images/users/user-3.jpg',
        name: 'Jessica T. Phillips',
        subject: 'Item Support Message sent',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'Medium',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#3653',
        requestuser: 'assets/images/users/user-4.jpg',
        name: 'Luke J. Sain',
        subject: 'Your password has been resett',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'Low',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#3654',
        requestuser: 'assets/images/users/user-2.jpg',
        name: 'Robert K. Joseph',
        subject: 'Support for theme',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'Low',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#3658',
        requestuser: 'assets/images/users/user-9.jpg',
        name: 'Darrell J. Cook',
        subject: 'Christopher S. Ahmad',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'Medium',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#854',
        requestuser: 'assets/images/users/user-2.jpg',
        name: 'William L. Trent',
        subject: 'Your Profile has been accepted',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'High',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#9501',
        requestuser: 'assets/images/users/user-10.jpg',
        name: 'Amy R. Barnaby',
        subject: 'Homeworth for your property increased',
        assignuser: 'assets/images/users/user-3.jpg',
        priority: 'Low',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    },
    {
        id: '#9852',
        requestuser: 'assets/images/users/user-5.jpg',
        name: 'Debra J. Wilson',
        subject: 'Your item has been updated!',
        assignuser: 'assets/images/users/user-10.jpg',
        priority: 'High',
        fname: 'Erwin',
        lname: 'Brown',
        birthdate: '1983/08/11',
        email: 'erwin@rmail.com',
        zipcode: '12345',
        status: 'Expired',
        createddate: '2020/04/30',
        duedate: '2020/08/07',
    }
];

export { cardData, tableData };

